<?php

namespace Container2aszLte;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FvQlVb4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FvQlVb4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FvQlVb4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'flasher' => ['privates', 'flasher.sweetalert', 'getFlasher_SweetalertService', false],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'doctrine' => '?',
            'flasher' => '?',
        ]);
    }
}
