<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZT7OXbq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZT7OXbq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZT7OXbq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZT7OXbq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZT7OXbq\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZT7OXbq',
    'container.build_id' => '0a919c71',
    'container.build_time' => 1663935652,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZT7OXbq');
